In [1]:

import requests

import pandas as pd
from pandas import json_normalize

from beak.experimental.cdr import download_evidence_layers

# Read data

## From CDR

In [2]:
token = ""

### CMA

In [3]:
url = "https://api.cdr.land/v1/prospectivity/cma?cma_id=ESRI%3A102008_b2f8589dda1a9471873ad66d40bda90a72e7713f09bbee1ac1231ef61c838227__res0_5000_res1_5000_Tungsten"

headers = {
    'accept': 'application/json',
    'Authorization': f'Bearer {token}'
}

response = requests.get(url, headers=headers)

data = response.json()
data = json_normalize(data)

df_cma = pd.DataFrame(data)
df_cma

,crs,mineral,download_url,cma_id,resolution,description,cogs,extent.type,extent.coordinates
0,ESRI:102008,Tungsten,https://s3.amazonaws.com/public.cdr.land/prosp...,ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...,"[500.0, 500.0]",Surprise 12-month hackathon MPM,[],MultiPolygon,"[[[[-1967803.0, 625862.0], [-1371281.0, 484886..."

### Model run

In [4]:
url = f"https://api.cdr.land/v1/prospectivity/model_run?model_run_id=7da530e4bf5f489d8cea6063a9aad8c1"

headers = {
    'accept': 'application/json',
    'Authorization': f'Bearer {token}'
}

response = requests.get(url, headers=headers)
data = response.json()

df = pd.DataFrame(data)
df

,system_version,model_type,system,model_run_id,cma_id,event
event,,SOM,,7da530e4bf5f489d8cea6063a9aad8c1,ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...,prospectivity_model_run.process
event_id,,SOM,,7da530e4bf5f489d8cea6063a9aad8c1,ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...,5628fc5d8ba64c71a0b20f40533e9c32
payload,,SOM,,7da530e4bf5f489d8cea6063a9aad8c1,ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...,"{'train_config': {'grid_type': 'rectangular', ..."
timestamp,,SOM,,7da530e4bf5f489d8cea6063a9aad8c1,ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...,2024-08-19T19:37:13.544791419Z

### Layers

In [5]:
df_payloads = df.loc["payload"]
df_payloads

system_version
model_type                                                      SOM
system
model_run_id                       7da530e4bf5f489d8cea6063a9aad8c1
cma_id            ESRI:102008_b2f8589dda1a9471873ad66d40bda90a72...
event             {'train_config': {'grid_type': 'rectangular', ...
Name: payload, dtype: object

In [10]:
event = df_payloads["event"]["evidence_layers"]
df_event = json_normalize(event)
df_event

,transform_methods,title,data_source.evidence_layer_raster_prefix,data_source.format,data_source.description,data_source.reference_url,data_source.type,data_source.resolution,data_source.derivative_ops,data_source.download_url,data_source.publication_date,data_source.subcategory,data_source.category,data_source.data_source_id,data_source.authors,data_source.DOI
0,[],Geophysics_Gravity_Bouguer_HGM,Geophysics_Gravity_Bouguer_HGM,tif,Gravity Bouguer,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2118.0, 2118.0]",HGM,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,gravity,geophysics,Geophysics_Gravity_Bouguer_HGM_res0_211779_res...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
1,[],Geophysics_Gravity_Bouguer_Up30km,Geophysics_Gravity_Bouguer_Up30km,tif,Gravity Bouguer upward continued (30km),https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2118.0, 2118.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,gravity,geophysics,Geophysics_Gravity_Bouguer_Up30km_res0_211779_...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
2,[],Geophysics_Gravity_Bouguer_Up30km_HGM,Geophysics_Gravity_Bouguer_Up30km_HGM,tif,Gravity Bouguer upward continued (30km),https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2118.0, 2118.0]",HGM,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,gravity,geophysics,Geophysics_Gravity_Bouguer_Up30km_HGM_res0_211...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
3,[],Geophysics_Gravity_Isostatic,Geophysics_Gravity_Isostatic,tif,Isostatic Gravity,,continuous,"[3892.0, 3892.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,1900-01-01T00:00:00,gravity,geophysics,Geophysics_Gravity_Isostatic_res0_389199_res1_...,[],
4,[],Geophysics_Gravity_Isostatic_HGM,Geophysics_Gravity_Isostatic_HGM,tif,Isostatic Gravity,,continuous,"[3892.0, 3892.0]",HGM,https://s3.amazonaws.com/public.cdr.land/prosp...,1900-01-01T00:00:00,gravity,geophysics,Geophysics_Gravity_Isostatic_HGM_res0_389199_r...,[],
5,[],Geophysics_MT2023_15km,Geophysics_MT2023_15km,tif,15km,https://ds.iris.edu/files/products/emc/emc-fil...,continuous,"[8715.0, 8715.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-01-01T00:00:00,magnetotellurics,geophysics,Geophysics_MT2023_15km_res0_87150_res1_87150_c...,"[Murphy, B.S., Bedrosian, P., Kelbert, A.]",
6,[],Geophysics_MT2023_9km,Geophysics_MT2023_9km,tif,9km,https://ds.iris.edu/files/products/emc/emc-fil...,continuous,"[8715.0, 8715.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-01-01T00:00:00,magnetotellurics,geophysics,Geophysics_MT2023_9km_res0_87150_res1_87150_ca...,"[Murphy, B.S., Bedrosian, P., Kelbert, A.]",
7,[],Geophysics_Radiometric_Potassium,Geophysics_Radiometric_Potassium,tif,Potassium,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2000.0, 2000.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2022-08-08T00:00:00,radiometric,geophysics,Geophysics_Radiometric_Potassium_res0_20000_re...,"[McCafferty, A.E., and Connell, D.M.]",
8,[],Geophysics_Radiometric_Thorium,Geophysics_Radiometric_Thorium,tif,Thorium,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2000.0, 2000.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2022-08-08T00:00:00,radiometric,geophysics,Geophysics_Radiometric_Thorium_res0_20000_res1...,"[McCafferty, A.E., and Connell, D.M.]",
9,[],Geophysics_Radiometric_Uranium,Geophysics_Radiometric_Uranium,tif,Uranium,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[2000.0, 2000.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2022-08-08T00:00:00,radiometric,geophysics,Geophysics_Radiometric_Uranium_res0_20000_res1...,"[McCafferty, A.E., and Connell, D.M.]",
10,[],Geophysics_LAB,Geophysics_LAB,tif,Depth to LAB,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[6768.0, 6768.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,seismic,geophysics,Geophysics_LAB_res0_67684_res1_67684_cat_Layer...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
11,[],Geophysics_LAB_HGM,Geophysics_LAB_HGM,tif,Depth to LAB,,continuous,"[6768.0, 6768.0]",HGM,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,seismic,geophysics,Geophysics_LAB_HGM_res0_67684_res1_67684_cat_L...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
12,[],Geophysics_Moho,Geophysics_Moho,tif,Depth to Moho,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[16723.0, 16723.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,seismic,geophysics,Geophysics_Moho_res0_1672273_res1_1672273_cat_...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
13,[],Geophysics_Mag_RTP,Geophysics_Mag_RTP,tif,Magnetic RTP,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[771.0, 771.0]",,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,magnetics,geophysics,Geophysics_Mag_RTP_res0_7705_res1_7705_cat_Lay...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",
14,[],Geophysics_Mag_RTP_HGM,Geophysics_Mag_RTP_HGM,tif,Magnetic RTP,https://www.sciencebase.gov/catalog/file/get/6...,continuous,"[771.0, 771.0]",HGM,https://s3.amazonaws.com/public.cdr.land/prosp...,2023-08-14T00:00:00,magnetics,geophysics,Geophysics_Mag_RTP_HGM_res0_7705_res1_7705_cat...,"[McCafferty, A.E., San Juan, C.A., Lawley, C.J...",

In [7]:
cma_id = df_cma.loc[0, "cma_id"]
cma_name = "regional_tusk_great_basin_102008_500"

In [9]:
# Some layers do not want to be downloaded via Python commands but work as "click and download"
ignore_layers = ["Geophysics_Gravity_Isostatic", "Geophysics_Gravity_Isostatic_HGM"]

download_evidence_layers(
    data=df_event,
    cma=df_cma.loc[0].to_dict(),
    custom_cma_id=cma_name,
    verify_ssl=False,
    ignore=ignore_layers,
)

100%|██████████| 15/15 [02:26<00:00,  9.78s/it]